configfile: "config/config.yaml"

shell.executable("/bin/bash")
shell.prefix("set -euo pipefail; ")

include: "rules/sample_context.smk"
include: "rules/heatmap_context.smk"
include: "rules/input_fastq.smk"
include: "rules/preprocess.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/quantify.smk"
include: "rules/batch_corr.smk"
include: "rules/de_four_seasons.smk"
include: "rules/de_general.smk"
include: "rules/targets.smk"


rule pre_de:
    input:
        *PRE_DE_TARGETS


rule de_four_seasons:
    input:
        *FOUR_SEASONS_DE_TARGETS


rule de_general:
    input:
        *GENERAL_DE_TARGETS


rule heatmap_four_seasons:
    input:
        *HEATMAP_PDF_FOUR_SEASONS_TARGETS,
        *HEATMAP_XLSX_FOUR_SEASONS_TARGETS,
        *HEATMAP_ZSCORE_PDF_FOUR_SEASONS_TARGETS


rule heatmap_general:
    input:
        *HEATMAP_PDF_GENERAL_TARGETS,
        *HEATMAP_XLSX_GENERAL_TARGETS,
        *HEATMAP_ZSCORE_PDF_GENERAL_TARGETS


rule all:
    input:
        *PRE_DE_TARGETS,
        *FOUR_SEASONS_DE_TARGETS
